import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/redux/Provider";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import MobileNav from "../components/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Classic Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative" suppressHydrationWarning={true}>
        <Providers>
          <div className="w-full relative">
            <div className="sticky top-0 left-0 right-0 z-20 bg-[#fffffff2]">
              <NavBar />
            </div>
            {children}
            <Footer />
          </div>
          <div className="fixed inset-0 z-10 hidden bg-[#000000b8] backdrop-blur-[1px]">
            <MobileNav />
          </div>
        </Providers>
      </body>
    </html>
  );
}
