import "../globals.css";
import { Inter } from "next/font/google";
import Providers from "@/redux/Provider";
import NavBar from "../../components/NavBar";
import Footer from "../../components/Footer";
import MobileNav from "../../components/MobileNav";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Classic Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative" suppressHydrationWarning={true}>
        <Providers>
          <div className="w-full relative">
            <div className="sticky top-0 left-0 right-0 z-20 bg-[#fffffff2]">
              <NavBar />
            </div>
            {children}
            <Footer />
          </div>
          <div className="fixed inset-0 z-40 lg: hidden bg-[#000000b8] backdrop-blur-[1px]">
            <MobileNav />
          </div>
          <div className="fixed bottom-2 z-[30] right-5">
            <p className="border-[1px] border-blue-400 p-2 rounded-lg text-blue-500 bg-white">
              May I help you?
            </p>
            <Image
              src={"/chatbot2.png"}
              height={500}
              width={500}
              alt="chatbot"
              className="w-[5rem] h-[6rem]"
            />
          </div>
        </Providers>
      </body>
    </html>
  );
}
